In [10]:
import pandas as pd

In [11]:
news = pd.read_csv('ru_test.csv')
news

                                                 title  is_fake
0    Роскомнадзор представил реестр сочетаний цвето...        0
1    Ночью под Минском на президентской горе Белара...        0
2    Бывший спичрайтер Юрия Лозы рассказал о трудно...        0
3    Сельская церковь, собравшая рекордно низкое ко...        0
4    Акции Google рухнули после объявления о переза...        0
..                                                 ...      ...
995  Прокуратура заподозрила Явлинского в авторитар...        0
996  В День Победы стратегические ракетоносцы Ту-16...        0
997  СК возбудил дело против авиакомпании «Победа» ...        0
998  Криптомонетный двор Туркменистана выпустил юби...        0
999  Deutsche Bahn заплатит рекордный штраф за чтен...        0

[1000 rows x 2 columns]

In [12]:
# Посчитаем количество строк с метками 0 и 1
count_0 = (news['is_fake'] == 0).sum()
count_1 = (news['is_fake'] == 1).sum()

print(f"Количество строк с меткой 0: {count_0}")
print(f"Количество строк с меткой 1: {count_1}")

Количество строк с меткой 0: 1000
Количество строк с меткой 1: 0

In [13]:
news2 = pd.read_csv('ru_train.csv')
news2

                                                  title  is_fake
0     Москвичу Владимиру Клутину пришёл счёт за вмеш...        1
1     Агент Кокорина назвал езду по встречке житейск...        0
2     Госдума рассмотрит возможность введения секрет...        1
3     ФАС заблокировала поставку скоростных трамваев...        0
4     Против Навального завели дело о недоносительст...        1
...                                                 ...      ...
5753  Эдди Чемберс получил сотрясение мозга в бою с ...        0
5754  Правительство застроит Россию нефтепродуктопро...        0
5755  «Мне стыдно перед дедом»: новый канцлер ФРГ об...        1
5756   Туркмения в декабре начнет поставки газа в Китай        0
5757  Бывший тренер Локомотива возглавил нальчикский...        0

[5758 rows x 2 columns]

In [14]:
# Посчитаем количество строк с метками 0 и 1
count_0 = (news2['is_fake'] == 0).sum()
count_1 = (news2['is_fake'] == 1).sum()

print(f"Количество строк с меткой 0: {count_0}")
print(f"Количество строк с меткой 1: {count_1}")

Количество строк с меткой 0: 2879
Количество строк с меткой 1: 2879

In [ ]:
# Дублируем столбец title в новый столбец text
news2['text'] = news2['title']

# Меняем порядок столбцов
news2 = news2[['title', 'text', 'is_fake']]

# Сохраняем изменённый датафрейм в новый файл
news2.to_csv('ru_train_with_text.csv', index=False)

# Фильтруем строки, где is_fake == 1
fake_df = news2[news2['is_fake'] == 1]

# Сохраняем отфильтрованные данные в отдельный файл
fake_df.to_csv('final_dataset/final_ru_f2879.csv', index=False)

In [15]:
news3 = pd.read_csv('en_t3000_f3000.csv')
news3

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL
...,...,...,...,...
6330,4490,State Department says it can't find emails fro...,The State Department told the Republican Natio...,REAL
6331,8062,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,FAKE
6332,8622,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,FAKE
6333,4021,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",REAL
6334,4330,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,REAL

In [ ]:
# Оставляем только нужные столбцы
news3 = news3[['title', 'text', 'label']]

# Переименовываем столбец label в is_fake
news3 = news3.rename(columns={'label': 'is_fake'})

# Заменяем значения FAKE на 1, REAL на 0
news3['is_fake'] = news3['is_fake'].replace({'FAKE': 1, 'REAL': 0})

# Сохраняем результат в новый файл
news3.to_csv('final_dataset/final_en_t3000_f3000.csv', index=False)

C:\Users\user\AppData\Local\Temp\ipykernel_17600\1564084958.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  news3['is_fake'] = news3['is_fake'].replace({'FAKE': 1, 'REAL': 0})

In [17]:
news3

,title,text,is_fake
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",1
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,1
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,0
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",1
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,0
...,...,...,...
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,0
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,1
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,1
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",0
6334,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,0

In [19]:
news4 = pd.read_csv("en_t21417.csv")
news4

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [ ]:
# Оставляем только нужные столбцы
news4 = news4[['title', 'text']]

# Добавляем столбец is_fake и заполняем его нулями
news4['is_fake'] = 0

# Сохраняем изменённый датафрейм в новый файл
news4.to_csv('final_dataset/final_en_t21417.csv', index=False)

C:\Users\user\AppData\Local\Temp\ipykernel_17600\3992922381.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  news4['is_fake'] = 0

In [23]:
news5= pd.read_csv("en_f23502.csv")
news5

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016"

In [27]:
# Оставляем только нужные столбцы
news5 = news5[['title', 'text']]

# Добавляем столбец is_fake и заполняем его единицами
news5['is_fake'] = 1

# Сохраняем изменённый датафрейм в новый файл
news5.to_csv('final_dataset/final_en_f23502.csv', index=False)

In [25]:
news5

,title,text,is_fake
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,1
...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,1
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,1
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,1
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,1
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,1